# Build Jekyll configuration
# These settings override _config.yml on `gulp build`

# Hides your drafts and future posts
future: false
show_drafts: false
# Gives you more accurate related posts
# lsi: true
# Removes the upper limit for posts generated
limit_posts: 0

source: 'src'
destination: 'serve'
