# Base Jekyll configuration

# Grunt handles some Jekyll configuration. If you set something here and
# it doesn't work, check if it is set in the Gruntfile.

# Use _config.build.yml to override these settings on `gulp build`.

name: Lewis Nyman
description: Lewis Nyman's personal thinking spot.
url: http://lewisnyman.co.uk

author:
  name: Lewis Nyman
  email: hello@lewisnyman.co.uk
  github: lewisnyman
  twitter: lewisnyman
  facebook: https://facebook.com/lewisnyman

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: src
destination: serve

# Exclude directories and/or files from the conversion.
# Gulp moves image files and asset directories.
exclude: ['vendor', 'img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg']

keep_files: ['assets/images']

# Force inclusion of directories and/or files in the conversion.
# .htaccess is a good example since dotfiles are excluded by default.
include: ['.htaccess']

# Default post path style
# date  /:categories/:year/:month/:day/:title.html
# pretty  /:categories/:year/:month/:day/:title/
# none  /:categories/:title.html
permalink: /blog/:title/

# _config.build.yml overwrites these options when you run `gulp build`
# Enables future posts (posts with dates in the future) and drafts
future: true
show_drafts: true
# Disables the more accurate related posts for faster generating of the site
lsi: false
# Only make the last 20 posts so generating isn't slow
limit_posts: 20
# Incremental builds
incremental: true

# Markdown library
markdown: redcarpet
# Markdown library options
# redcarpet:
  # extensions: ['fenced_code_blocks', 'smart']

# Highlight code blocks
highlighter: null

plugins:
  - jekyll-time-to-read
