source "http://rubygems.org"

gem 'jekyll'
gem 'redcarpet'
gem 'csscss'
gem 'sass'
gem 'compass'
gem "breakpoint"
gem "animation"
gem 'RedCloth'
gem 'thin'
gem 'sass-globbing'
gem 'jekyll-compose'
gem 'jekyll-time-to-read'
gem 'jekyll-crosspost-to-medium'
